config/routes.rb
Rails.application.routes.draw do

  get 'serach/index'

  post 'serach/search'

  get 'list_g/index'

  resources :searches
  get 'tuti/index'

  get 'rink/index'

  resources :categories
  resources :syoji_ts
  resources :genres

  resources :syojis
  resources :syojis do
    member do
      get 'show_image'
    end
  end
  get 'menu/index'

  get 'logins/index'
  get 'logins/logoff'
  #resources :logins
  post 'logins/auth'
  resources :sche_ts
  resources :icons
  resources :icons do
    member do
      get'show_image'
    end 
  end
  resources :sches
  resources :users
  resources :users do
    member do
      get 'show_image'
    end
  end
  resources :genres
  resources :genres do
    member do
      get 'show_image'
    end
  end
  root 'tuti#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :syojis

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :syojis, :foreign_key => "color_id"
end

app/models/icon.rb
class Icon < ApplicationRecord
  validate :error_check
  has_many :sches  
  def error_check
  end
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/sche.rb
class Sche < ApplicationRecord
  validate :error_check

  has_many :sche_ts

  belongs_to :icon

  def error_check
    # name_sche が空のときにエラーメッセージ
    if name_sche.blank?
       errors[:base] << '予定名は必ず入力してください'
    end

    # schedule_at が過去日のときエラーメッセージ
    if schedule_at < Time.now
      errors[:base] << '過去日は選択できません'
    end

    # notification_time が過去日か予定日以降のときエラーメッセージ
    if notification_sche == true or mail_sche == true
      if notification_time < Time.now
        errors[:base] << '過去日は選択できません'
      else
        if notification_time > schedule_at
          errors[:base] << '予定日より後は選択できません'
        end
      end
    end

  end

end

app/models/sche_t.rb
class ScheT < ApplicationRecord

  belongs_to :Sche

end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/syoji.rb
class Syoji < ApplicationRecord

    belongs_to :category
    belongs_to :genre, :foreign_key => "color_id"

    validate :error_check
    def error_check
      # title_syo が空のときにエラーメッセージ
      if title_syo.blank?
        errors[:base] << 'タイトルは必ず入力してください'
      end

      # notification_time が過去日か発売日以降のときエラーメッセージ
      if have == 3
        if notification_syo == true or mail_syo == true
          if notification_time < Time.now
              errors[:base] << '過去日は選択できません'
          else
            if notification_time > release
              errors[:base] << '発売日より後は選択できません'
            end
          end
        end
      end

      if have.blank?
        errors[:base] << '所持状態を入力してください'
      end
    end

end

app/models/syoji_t.rb
class SyojiT < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    validate :error_check
    def error_check

        if name_user.blank?
            errors[:base] << 'ユーザー名は必ず入力してください' 
        else
            if name_user.split(//).size > 20
                errors[:base] << 'ユーザー名は20文字以内で入力してください'
            end
        end
        if mail_user.blank?
            errors[:base] << 'メールアドレスは必ず入力してください'
        end
        if pass_user.blank?
            errors[:base] << 'パスワードは必ず入力してください'
        else
            if pass_user.split(//).length < 8
                errors[:base] << 'パスワードは８文字以上入力してください'
            end
        end
        unless pass_user.blank?
            a="#{pass_user}"=~/^[ぁ-んァ-ン一-龥]/
            if a != nil
                errors[:base] << 'パスワードは英数字のみで入力してください'
            end
        end
        unless mail_user.blank?
            a="#{mail_user}"=~/^[ぁ-んァ-ン一-龥]/
            if a != nil
                errors[:base] << 'メールアドレスは英数字のみで入力してください'
            end
        end
        unless mail_user.blank?
            a="#{mail_user}"=~/^[a-zA-Z0-9]+$/
            if a == nil
                errors[:base] << 'メールアドレスは半角で入力してください'
            end
        end
        unless pass_user.blank?
            a="#{pass_user}"=~/^[a-zA-Z0-9]+$/
            if a == nil
                errors[:base] << 'パスワードは半角で入力してください'
            end
        end


        #unless image_user.blank? 
            #case File.extname(image_user)
            #when ".png",".jpg",".jpeg",".bmp"
             #else
             #errors[:base] << '登録できる拡張子は png, jpg, jpeg,bmp です'
            #end
        #end
    end
    def self.authenticate(mail_user,pass_user)
        usr = find_by(mail_user: mail_user)
        if usr != nil && usr.pass_user == pass_user then
            usr
        else
            return
        end
    end
end

app/controllers/syoji_ts_controller.rb
class SyojiTsController < ApplicationController
  before_action :set_syoji_t, only: [:show, :edit, :update, :destroy]

  # GET /syoji_ts
  # GET /syoji_ts.json
  def index
    @syoji_ts = Syoji.where(user_id: session[:usr]).order(notification_time: "DESC")
  end

  # GET /syoji_ts/1
  # GET /syoji_ts/1.json
  def show
  end

  # GET /syoji_ts/new
  def new
  end

  # GET /syoji_ts/1/edit
  def edit
  end

  # POST /syoji_ts
  # POST /syoji_ts.json
  def create
    @syoji_t = SyojiT.new(syoji_t_params)

    respond_to do |format|
      if @syoji_t.save
        format.html { redirect_to @syoji_t, notice: 'Syoji t was successfully created.' }
        format.json { render :show, status: :created, location: @syoji_t }
      else
        format.html { render :new }
        format.json { render json: @syoji_t.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /syoji_ts/1
  # PATCH/PUT /syoji_ts/1.json
  def update
    respond_to do |format|
      if @syoji_t.update(syoji_t_params)
        format.html { redirect_to @syoji_t, notice: 'Syoji t was successfully updated.' }
        format.json { render :show, status: :ok, location: @syoji_t }
      else
        format.html { render :edit }
        format.json { render json: @syoji_t.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syoji_ts/1
  # DELETE /syoji_ts/1.json
  def destroy
    @syoji_t.destroy
    respond_to do |format|
      format.html { redirect_to syoji_ts_url, notice: 'Syoji t was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_syoji_t
      @syoji_t = SyojiT.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def syoji_t_params
      params.require(:syoji_t).permit(:release, :title, :artist)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/list_g_helper.rb
module ListGHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/rink_helper.rb
module RinkHelper
end

app/helpers/sches_helper.rb
module SchesHelper
end

app/helpers/serach_helper.rb
module SerachHelper
end

app/helpers/syoji_t_helper.rb
module SyojiTHelper
end

app/helpers/syoji_ts_helper.rb
module SyojiTsHelper
end

app/helpers/syojis_helper.rb
module SyojisHelper
end

app/helpers/tuti_helper.rb
module TutiHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/syoji_ts/_form.html.erb
<%= form_with(model: syoji_t, local: true) do |form| %>
  <% if syoji_t.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(syoji_t.errors.count, "error") %> prohibited this syoji_t from being saved:</h2>

      <ul>
      <% syoji_t.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :release %>
    <%= form.date_select :release, id: :syoji_t_release %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :syoji_t_title %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :syoji_t_artist %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/syoji_ts/edit.html.erb
<h1>Editing Syoji T</h1>

<%= render 'form', syoji_t: @syoji_t %>

<%= link_to 'Show', @syoji_t %> |
<%= link_to 'Back', syoji_ts_path %>

app/views/syoji_ts/index.html.erb
<p id="notice"><%= notice %></p>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="box14"><h1>発売日通知</h1></div>

<% kensu = 0 %>
<% @syoji_ts.each do |syoji_t| %>
  <% if syoji_t.release.present? %>
    <% if syoji_t.release >= Date.today and syoji_t.release <= Date.today + 5
       kensu += 1
    end %>
  <% end %>
<% end %>
<p><div class="box2"><strong>５日以内に発売するものが <%= kensu %> 件あります</strong></div></p>

<table>
  <thead>
    <tr>
      <div class="box14"><p>発売日</p></div>
      <th>タイトル</th>
      <th>アーティスト名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @syoji_ts.each do |syoji_t| %>
      <% if syoji_t.notification_syo == true %>
      <% if syoji_t.release.present? %>
        <% if syoji_t.notification_time <= DateTime.now %>
          <% if syoji_t.release < Date.today
               namecolor = "red"
             end
          %>
        <tr>
          <td style = "color : <%= namecolor %>"><%= syoji_t.release.strftime('20%y/%m/%d') %></td>
          <td><%= syoji_t.title_syo %></td>
          <td><%= syoji_t.artist %></td>
          <td><%= link_to '詳細', syoji_t %></td>
          <td><%= link_to '編集', edit_syoji_path(syoji_t) %></td>
          <td><%= link_to '削除', syoji_t, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/syoji_ts/new.html.erb
<h1>New Syoji T</h1>

<%= render 'form', syoji_t: @syoji_t %>

<%= link_to 'Back', syoji_ts_path %>

app/views/syoji_ts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Release:</strong>
  <%= @syoji_t.release %>
</p>

<p>
  <strong>Title:</strong>
  <%= @syoji_t.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @syoji_t.artist %>
</p>

<%= link_to 'Edit', edit_syoji_t_path(@syoji_t) %> |
<%= link_to 'Back', syoji_ts_path %>