config/routes.rb
Rails.application.routes.draw do

  get 'serach/index'

  post 'serach/search'

  get 'list_g/index'

  resources :searches
  get 'tuti/index'

  get 'rink/index'

  resources :categories
  resources :syoji_ts
  resources :genres

  resources :syojis
  resources :syojis do
    member do
      get 'show_image'
    end
  end
  get 'menu/index'

  get 'logins/index'
  get 'logins/logoff'
  #resources :logins
  post 'logins/auth'
  resources :sche_ts
  resources :icons
  resources :icons do
    member do
      get'show_image'
    end 
  end
  resources :sches
  resources :users
  resources :users do
    member do
      get 'show_image'
    end
  end
  resources :genres
  resources :genres do
    member do
      get 'show_image'
    end
  end
  root 'tuti#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/syoji.rb
class Syoji < ApplicationRecord

    belongs_to :category
    belongs_to :genre, :foreign_key => "color_id"

    validate :error_check
    def error_check
      # title_syo が空のときにエラーメッセージ
      if title_syo.blank?
        errors[:base] << 'タイトルは必ず入力してください'
      end

      # notification_time が過去日か発売日以降のときエラーメッセージ
      if have == 3
        if notification_syo == true or mail_syo == true
          if notification_time < Time.now
              errors[:base] << '過去日は選択できません'
          else
            if notification_time > release
              errors[:base] << '発売日より後は選択できません'
            end
          end
        end
      end

      if have.blank?
        errors[:base] << '所持状態を入力してください'
      end
    end

end

app/controllers/syojis_controller.rb
class SyojisController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_syoji, only: [:show, :edit, :update, :destroy]

  # GET /syojis
  # GET /syojis.json
  def index
    @syojis1 = Syoji.where(have: '1').where(user_id: session[:usr]).order(sort_column + ' ' + sort_direction)
    @syojis2 = Syoji.where(have: '2').where(user_id: session[:usr]).order(sort_column + ' ' + sort_direction)
    @syojis3 = Syoji.where(have: '3').where(user_id: session[:usr]).order(sort_column + ' ' + sort_direction)
  end

  # GET /syojis/1
  # GET /syojis/1.json
  def show
  end

  # GET /syojis/new
  def new
    @syoji = Syoji.new
  end

  # GET /syojis/1/edit
  def edit
  end

  # POST /syojis
  # POST /syojis.json
  def create
    @syoji = Syoji.new
    @syoji.title_syo         = params[:syoji][:title_syo]
    @syoji.volume            = params[:syoji][:volume]
    @syoji.artist            = params[:syoji][:artist]

    @syoji.color_id           = params[:syoji][:color_id]
    @syoji.title_j           = params[:syoji][:title_j]

    if params[:syoji][:image_syo].present?
      @syoji.image_syo = params[:syoji][:image_syo].original_filename
      @syoji.image_type = params[:syoji][:image_syo].content_type
      @syoji.image_binary = params[:syoji][:image_syo].read
    end

    @syoji.memo_syo          = params[:syoji][:memo_syo]
    @syoji.url_syo           = params[:syoji][:url_syo]
    @syoji.have              = params[:syoji][:have]
    @syoji.volume_have       = params[:syoji][:volume_have]

    if @syoji.have == 3
      @syoji.release           = Date.new(params[:syoji][:'release(1i)'].to_i,
                                          params[:syoji][:'release(2i)'].to_i,
                                          params[:syoji][:'release(3i)'].to_i,)
      @syoji.notification_syo  = params[:syoji][:notification_syo]
      #@syoji.mail_syo          = params[:syoji][:mail_syo] 
      if @syoji.notification_syo == true #or @syoji.mail_syo == true     
        @syoji.notification_time = DateTime.new(params[:syoji][:'notification_time(1i)'].to_i,
                                                params[:syoji][:'notification_time(2i)'].to_i,
                                                params[:syoji][:'notification_time(3i)'].to_i,
                                                params[:syoji][:'notification_time(4i)'].to_i,
                                                params[:syoji][:'notification_time(5i)'].to_i,
                                                00)
        #@syoji.snooze            = params[:syoji][:snooze]
      end
    end

    @syoji.category_id       = params[:syoji][:category_id]
    
    if session[:usr].present?
      @syoji.user_id = session[:usr]
    end

    if @syoji.save
      redirect_to syojis_path
    else
      render :new
    end
  end

  # PATCH/PUT /syojis/1
  # PATCH/PUT /syojis/1.json
  def update
    @syoji = Syoji.find(params[:id])
    @syoji.title_syo         = params[:syoji][:title_syo]
    @syoji.volume            = params[:syoji][:volume]
    @syoji.artist            = params[:syoji][:artist]

    @syoji.color_id           = params[:syoji][:color_id]
    @syoji.title_j           = params[:syoji][:title_j]

    if params[:syoji][:image_syo].present?
      @syoji.image_syo = params[:syoji][:image_syo].original_filename
      @syoji.image_type = params[:syoji][:image_syo].content_type
      @syoji.image_binary = params[:syoji][:image_syo].read
    end

    @syoji.memo_syo          = params[:syoji][:memo_syo]
    @syoji.url_syo           = params[:syoji][:url_syo]
    @syoji.have              = params[:syoji][:have]
    @syoji.volume_have       = params[:syoji][:volume_have]

    if @syoji.have == 3
      @syoji.release           = Date.new(params[:syoji][:'release(1i)'].to_i,
                                          params[:syoji][:'release(2i)'].to_i,
                                          params[:syoji][:'release(3i)'].to_i,)
      @syoji.notification_syo  = params[:syoji][:notification_syo]
      #@syoji.mail_syo          = params[:syoji][:mail_syo]
      if @syoji.notification_syo == true #or @syoji.mail_syo == true
        @syoji.notification_time = DateTime.new(params[:syoji][:'notification_time(1i)'].to_i,
                                                params[:syoji][:'notification_time(2i)'].to_i,
                                                params[:syoji][:'notification_time(3i)'].to_i,
                                                params[:syoji][:'notification_time(4i)'].to_i,
                                                params[:syoji][:'notification_time(5i)'].to_i,
                                                00)
        #@syoji.snooze            = params[:syoji][:snooze]
      end
    end

    @syoji.category_id       = params[:syoji][:category_id]
    
    if session[:usr].present?
      @syoji.user_id = session[:usr]
    end

    if @syoji.save
      redirect_to syojis_path
    else
      render :edit
    end
  end

  def show_image
    @syoji = Syoji.find(params[:id])
    send_data @syoji.image_binary, :filename => @syoji.image_syo, :type => @syoji.image_type, :disposition => 'inline'
  end

  # DELETE /syojis/1
  # DELETE /syojis/1.json
  def destroy
    @syoji = Syoji.find(params[:id])
    @syoji.destroy

    redirect_to syojis_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_syoji
      @syoji = Syoji.find(params[:id])
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
 
    def sort_column
      Syoji.column_names.include?(params[:sort]) ? params[:sort] : "title_syo"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def syoji_params
      params.require(:syoji).permit(:title_syo, :volume, :artist, :color_id, :title_j, :image_syo, :image_binary, :image_type, :memo_syo, :url_syo, :have, :volume_have, :release, :notification_syo, :mail_syo, :notification_time, :snooze, :category_id, :user_id)
    end
end

app/helpers/syojis_helper.rb
module SyojisHelper
end

app/views/syojis/_form.html.erb
<%= form_with(model: syoji, local: true) do |form| %>
  <% if syoji.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(syoji.errors.count, "error") %> prohibited this syoji from being saved:</h2>

      <ul>
      <% syoji.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :タイトル＊ %>
    <%= form.text_field :title_syo, id: :syoji_title_syo %>
  </div>

  <div class="field">
    <%= form.label :アーティスト名 %>
    <%= form.text_field :artist, id: :syoji_artist %>
  </div>

  <div class="field">
    <%= form.label :カテゴリー %>
    <%= form.select :category_id, Category.all.map { |c|[c.category, c.id] } %>
  </div>

  <div class="field">
    <%= form.label :ジャンルカラー %>
    <% i = 0 %>
    <% Genre.all.map {|g| %>
    <% i = i+1 %>
     <span><%= form.radio_button :color_id, g.id %><%= image_tag  g.image_g  ,:width => 37  %></span>
     <% if i == 4 %>
     <BR>
     <% i = 0 %>
     <% end %>

    <% } %>
  </div>

  <div class="field">
    <%= form.label :ジャンルタイトル %>
    <%= form.text_field :title_j, id: :syoji_title_j %>
  </div>

  <div class="field">
    <%= form.label :ジャケット画像 %>
    <%= form.file_field :image_syo, id: :syoji_image_syo %>
  </div>

  <div class="field">
    <%= form.label :メモ %>
    <%= form.text_area :memo_syo, id: :syoji_memo_syo %>
  </div>

  <div class="field">
    <%= form.label :HPリンク %>
    <%= url_field :syoji, :url_syo %>
  </div>


  <div class="field">
    <%= form.label :所持状態＊ %>
    <%= form.label :持っている %>
    <%= form.radio_button(:have, "1")%>
    <%= form.label :欲しい（発売済み） %>
    <%= form.radio_button(:have, "2")%>
    <%= form.label :欲しい（未発売） %>
    <%= form.radio_button(:have, "3")%>
  </div>

  <div class="field">
    <%= form.label :所持巻数 %>
    <%= number_field(:syoji, :volume_have, in: 1.0..200, step: 1) %>
  </div>

  <div class="field">
    <%= form.label :求巻数 %>
    <%= number_field(:syoji, :volume, in: 1.0..200, step: 1) %>
  </div>

  <div class="field">
    <%= form.label :発売日 %>
    <%= form.date_select :release, id: :syoji_release %>
  </div>

  <div class="field">
    <%= form.label :アプリ内通知 %>
    <%= form.check_box :notification_syo, id: :syoji_notification_syo %>
  </div>

<!--
  <div class="field">
    <%= form.label :メール通知 %>
    <%= form.check_box :mail_syo, id: :syoji_mail_syo %>
  </div>
-->

  <div class="field">
    <%= form.label :通知時間（通知がオフ時不要） %>
    <%= form.datetime_select :notification_time, id: :syoji_notification_time %>
  </div>

<!--
  <div class="field">
  <%= form.label :スヌーズ（通知がオフ時不要） %>
  <%= form.check_box :snooze, id: :syoji_snooze %>
　</div>
-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/syojis/edit.html.erb
<h1>編集</h1>

<%= render 'form', syoji: @syoji %>

<%= link_to '戻る', :back , target:"_self" %>|
<%= link_to '詳細', @syoji , target:"_self" %> 

app/views/syojis/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box14"><h1>グッズ</h1></div>

<h4><%= link_to '新規追加', new_syoji_path , target:"_self" %> </h4>

<table>
  <thead>
  <br><div class="box17"><h2>持っている</h2></div>
    <tr>
    <div class="box22"><th><%= sortable "title_syo", "タイトル" %></th></div>
    <div class="box22"><th><%= sortable "artist", "アーティスト名" %></th></div>
    <div class="box22"><th>ジャケット</th></div>
    <th></th>
    <th></th>
    <th></th>    
    </tr>
  </thead>
  <tbody>
    <% @syojis1.each do |syoji| %>
      <tr>
      <td><%= syoji.title_syo %>
      <td><%= syoji.artist %>
      <td><% if syoji.image_syo.present? %>
          <%= image_tag show_image_syoji_path(syoji), :height =>60 %>
        <% else %>
        <% end %>
        <td><%= link_to '詳細', syoji, target:"_self" %>
        <td><%= link_to '編集', edit_syoji_path(syoji), target:"_self" %>
        <td><%= link_to '削除', syoji, method: :delete, data: { confirm: '削除しますか？' } %>
      </tr>
    <% end %>
  </tbody>
</table>


<table>
<thead>
<br><div class="box17"><h2>欲しい（発売済み）</h2></div>
  <tr>
  <div class="box22"><th><%= sortable "title_syo", "タイトル" %></th></div>
  <div class="box22"><th><%= sortable "artist", "アーティスト名" %></th></div>
  <div class="box22"><th>ジャケット</th></div>
  <th></th>
  <th></th>
  <th></th>  
  </tr>
</thead>
<tbody>
  <% @syojis2.each do |syoji| %>
    <tr>
    <td><%= syoji.title_syo %>
    <td><%= syoji.artist %>
    <td><% if syoji.image_syo.present? %>
        <%= image_tag show_image_syoji_path(syoji), :height =>60 %>
      <% else %>
      <% end %>
          <td><%= link_to '詳細', syoji, target:"_self" %>
          <td><%= link_to '編集', edit_syoji_path(syoji), target:"_self" %>
          <td><%= link_to '削除', syoji, method: :delete, data: { confirm: '削除しますか？' } %>
    </tr>
  <% end %>
</tbody>
</table>


<table>
<thead>
<br><div class="box17"><h2>欲しい（未発売）</h2></div>
  <tr>
  <div class="box22"><th><%= sortable "title_syo", "タイトル" %></th></div>
  <div class="box22"><th><%= sortable "artist", "アーティスト名" %></th></div>
  <div class="box22"><th>ジャケット</th></div>
  <div class="box22"><th><%= sortable "release", "発売日"%></th></div>
  <th></th> 
  <th></th> 
  <th></th> 
  </tr>
</thead>
<tbody>
  <% @syojis3.each do |syoji| %>
    <tr>
    <td><%= syoji.title_syo %></td>
    <td><%= syoji.artist %></td>
    <td><% if syoji.image_syo.present? %>
        <%= image_tag show_image_syoji_path(syoji), :height =>60 %>
      <% else %>
      <% end %>
     <td><% if syoji.release.present? %>
            <%= syoji.release.strftime('20%y/%m/%d') %>
     <% end %>
          <td><%= link_to '詳細', syoji, target:"_self" %>
          <td><%= link_to '編集', edit_syoji_path(syoji), target:"_self" %>
          <td><%= link_to '削除', syoji, method: :delete, data: { confirm: '削除しますか？' } %>
    </tr>
  <% end %>
</tbody>
</table>

<br>

<h4><%= link_to '新規追加', new_syoji_path , target:"_self" %> </h4>

app/views/syojis/new.html.erb
<h1>新規追加</h1>

<%= render 'form', syoji: @syoji %>

<%= link_to '戻る', :back , target:"_self" %>

app/views/syojis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong>
  <%= @syoji.title_syo %>
</p>

<p>
  <strong>アーティスト名：</strong>
  <%= @syoji.artist %>
</p>

<p>
  <strong>ジャンルカラー：</strong>
  <% if @syoji.color_id.present? %>
    <%= image_tag show_image_genre_path(@syoji.genre), :width => 50 %>
  <% end %>
</p>

<p>
  <strong>カテゴリー：</strong>
  <%= @syoji.category.category %>
</p>

<p>
  <strong>ジャンルタイトル：</strong>
  <%= @syoji.title_j %>
</p>

<p>
  <strong>ジャケット画像：</strong>
  <% if @syoji.image_syo.present? %>
    <%= image_tag show_image_syoji_path(@syoji), :height =>60 %>
  <% end %>
</p>

<p>
  <strong>メモ：</strong>
  <%= @syoji.memo_syo %>
</p>

<p>
  <strong>リンク：</strong>
  <%= link_to @syoji.url_syo, @syoji.url_syo %>
</p>

<p>
<strong>所持状態：</strong>
  <% case @syoji.have %>
    <% when 1 %>
      持っている
    <% when 2 %>
      欲しい（発売済み）
    <% when 3 %>
      欲しい（未発売）
  <% end %>
</p>

<p>
<strong>所持巻数：</strong>
  <%= @syoji.volume_have %>
  <% if @syoji.volume_have.present? %>
     巻
  <% end %>
</p>

<p>
<% if @syoji.have != 1 %>
<strong>欲しい巻数：</strong>
  <%= @syoji.volume %>
  <% if @syoji.volume.present? %>
     巻
  <% end %>
<% end %>
</p>

<% if @syoji.have == 3 %>
<p>
<strong>発売日：</strong>
<%= @syoji.release %>
</p>

<p>
  <strong>アプリ内通知：</strong>
  <% if @syoji.notification_syo == true %>
    オン
  <% else %>
    オフ
  <% end %>
</p>

<!--
<p>
  <strong>メール通知：</strong>
  <% if @syoji.mail_syo == true %>
  オン
<% else %>
  オフ
<% end %>
</p>
-->

<p>
  <strong>通知時間：</strong>
  <% if @syoji.notification_syo == true %>
    <%= @syoji.notification_time.strftime('20%y/%m/%d %H:%M') %>
  <% end %>
</p>
<!--
<p>
<strong>スヌーズ：</strong>
<% if @syoji.notification_syo == true %>
  <% if @syoji.snooze == true %>
    オン
  <% else %>
    オフ
  <% end %>
<% end %>
</p>
-->
<% end %>

<%= link_to '一覧へ', syojis_path , target:"_self" %>|
<%= link_to '編集', edit_syoji_path(@syoji) , target:"_self" %> |
<%= link_to '通知画面へ', tuti_index_path , target:"_self" %> 