config/routes.rb
Rails.application.routes.draw do

  get 'serach/index'

  post 'serach/search'

  get 'list_g/index'

  resources :searches
  get 'tuti/index'

  get 'rink/index'

  resources :categories
  resources :syoji_ts
  resources :genres

  resources :syojis
  resources :syojis do
    member do
      get 'show_image'
    end
  end
  get 'menu/index'

  get 'logins/index'
  get 'logins/logoff'
  #resources :logins
  post 'logins/auth'
  resources :sche_ts
  resources :icons
  resources :icons do
    member do
      get'show_image'
    end 
  end
  resources :sches
  resources :users
  resources :users do
    member do
      get 'show_image'
    end
  end
  resources :genres
  resources :genres do
    member do
      get 'show_image'
    end
  end
  root 'tuti#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/sches_controller.rb
class SchesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_sch, only: [:show, :edit, :update, :destroy]

  # GET /sches
  # GET /sches.json
  def index
    @sches = Sche.where(user_id: session[:usr]).order(sort_column + ' ' + sort_direction)
  end

  # GET /sches/1
  # GET /sches/1.json
  def show
  end

  # GET /sches/new
  def new
    @sch = Sche.new
  end

  # GET /sches/1/edit
  def edit
  end

  # POST /sches
  # POST /sches.json
  def create
    @sch = Sche.new
    @sch.syujitsu          = params[:sche][:syujitsu]
    if @sch.syujitsu == true
      @sch.schedule_at       = Date.new(params[:sche][:'schedule_at(1i)'].to_i,
                                        params[:sche][:'schedule_at(2i)'].to_i,
                                        params[:sche][:'schedule_at(3i)'].to_i,
                                        )
    else
      @sch.schedule_at       = DateTime.new(params[:sche][:'schedule_at(1i)'].to_i,
                                          params[:sche][:'schedule_at(2i)'].to_i,
                                          params[:sche][:'schedule_at(3i)'].to_i,
                                          params[:sche][:'schedule_at(4i)'].to_i,
                                          params[:sche][:'schedule_at(5i)'].to_i,
                                          00)
    end
    @sch.name_sche         = params[:sche][:name_sche]
    @sch.icon_id           = params[:sche][:icon_id]
    @sch.place             = params[:sche][:place]
    @sch.memo_sche         = params[:sche][:memo_sche]

    @sch.notification_sche = params[:sche][:notification_sche]
    #@sch.mail_sche         = params[:sche][:mail_sche]

    if @sch.notification_sche == true #or @sch.mail_sche == true
      @sch.notification_time = DateTime.new(params[:sche][:'notification_time(1i)'].to_i,
                                            params[:sche][:'notification_time(2i)'].to_i,
                                            params[:sche][:'notification_time(3i)'].to_i,
                                            params[:sche][:'notification_time(4i)'].to_i,
                                            params[:sche][:'notification_time(5i)'].to_i,
                                            00)
      #@sch.snooze            = params[:sche][:snooze]
    end

    @sch.url_sche         = params[:sche][:url_sche]

    if session[:usr].present?
      @sch.user_id = session[:usr]
    end

    if @sch.save
      redirect_to sches_path
    else
      render :new
    end
  end

  # PATCH/PUT /sches/1
  # PATCH/PUT /sches/1.json
  def update
    @sch = Sche.find(params[:id])
    @sch.syujitsu          = params[:sche][:syujitsu]
    if @sch.syujitsu == true
      @sch.schedule_at       = Date.new(params[:sche][:'schedule_at(1i)'].to_i,
                                        params[:sche][:'schedule_at(2i)'].to_i,
                                        params[:sche][:'schedule_at(3i)'].to_i,
                                        )
    else
      @sch.schedule_at       = DateTime.new(params[:sche][:'schedule_at(1i)'].to_i,
                                          params[:sche][:'schedule_at(2i)'].to_i,
                                          params[:sche][:'schedule_at(3i)'].to_i,
                                          params[:sche][:'schedule_at(4i)'].to_i,
                                          params[:sche][:'schedule_at(5i)'].to_i,
                                          00)
    end
    @sch.name_sche         = params[:sche][:name_sche]
    @sch.icon_id           = params[:sche][:icon_id]
    @sch.place             = params[:sche][:place]
    @sch.memo_sche         = params[:sche][:memo_sche]

    @sch.notification_sche = params[:sche][:notification_sche]
    #@sch.mail_sche         = params[:sche][:mail_sche]

    if @sch.notification_sche == true #or @sch.mail_sche == true
      @sch.notification_time = DateTime.new(params[:sche][:'notification_time(1i)'].to_i,
                                            params[:sche][:'notification_time(2i)'].to_i,
                                            params[:sche][:'notification_time(3i)'].to_i,
                                            params[:sche][:'notification_time(4i)'].to_i,
                                            params[:sche][:'notification_time(5i)'].to_i,
                                            00)
      #@sch.snooze            = params[:sche][:snooze]
    end
    
    @sch.url_sche         = params[:sche][:url_sche]

    if session[:usr].present?
      @sch.user_id = session[:usr]
    end

    if @sch.save
      redirect_to sches_path
    else
      render :edit
    end
  end

  # DELETE /sches/1
  # DELETE /sches/1.json
  def destroy
    @sch = Sche.find(params[:id])
    @sch.destroy

    redirect_to sches_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sch
      @sch = Sche.find(params[:id])
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

    def sort_column
      Sche.column_names.include?(params[:sort]) ? params[:sort] : "schedule_at"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sch_params
      params.require(:sche).permit(:syujitsu, :schedule_at, :name_sche, :icon_id, :place, :memo_sche, :notification_sche, :mail_sche, :notification_time, :snooze, url_sche, :user_id)
    end
end

app/helpers/sches_helper.rb
module SchesHelper
end

app/views/sches/_form.html.erb
<%= form_with(model: sch, local: true) do |form| %>
  <% if sch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sch.errors.count, "error") %> prohibited this sch from being saved:</h2>

      <ul>
      <% sch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :終日 %>
    <%= form.check_box :syujitsu %>
  </div>

  <div class="field">
    <%= form.label :日時＊（終日を選択時は時間不要） %>
    <%= form.datetime_select :schedule_at %>
  </div>

  <div class="field">
    <%= form.label :予定名＊ %>
    <%= form.text_field :name_sche %>
  </div>


  <div class="field">
  <%= form.label :アイコン %>
  <% Icon.all.map {|i| %>
   <span><%= form.radio_button :icon_id, i.id %><%= image_tag  i.image_icon  ,:width => 37  %></span>
  <% } %>
</div>

  <div class="field">
    <%= form.label :場所 %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :メモ %>
    <%= form.text_area :memo_sche %>
  </div>

  <div class="field">
    <%= form.label :アプリ内通知 %>
    <%= form.check_box :notification_sche %>
  </div>

  <!--
  <div class="field">
    <%= form.label :メール通知 %>
    <%= form.check_box :mail_sche %>
  </div>
  -->

  <div class="field">
    <%= form.label :通知時間（通知がオフ時不要） %>    
    <%= form.datetime_select :notification_time %>
  </div>

<!--
  <div class="field">
    <%= form.label :スヌーズ（通知がオフ時不要） %>
    <%= form.check_box :snooze %>
  </div>
-->

  <div class="field">
    <%= form.label :HPリンク %>
    <%= url_field :sche, :url_sche %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/sches/edit.html.erb
<h1>編集</h1>

<%= render 'form', sch: @sch %>

<%= link_to '戻る', :back , target:"_self" %>  |
<%= link_to '詳細', @sch , target:"_self" %>

app/views/sches/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box14"><h1>スケジュール</h1></div>

<% today = Date.today %>
<% now = Date.current %>
<table border="1">
  <caption><%= now.strftime('%Y年%m月') %></caption>
  <tr height="30px">
    <th width="75px" style="background: #ff9ba0;"><spen style="color: white;"> 日</spen></th>
    <th width="75px" style="background: #a5d3fd"><spen style="color: white;">月</spen></th>
    <th width="75px" style="background: #a5d3fd;"><spen style="color: white;">火</spen></th>
    <th width="75px" style="background: #a5d3fd;"><spen style="color: white;">水</spen></th>
    <th width="75px" style="background: #a5d3fd;"><spen style="color: white;">木</spen></th>
    <th width="75px" style="background: #a5d3fd;"><spen style="color: white;">金</spen></th>
    <th width="75px" style="background: #76aeee;"><spen style="color: white;">土</spen></th>
  </tr>
  <tr>
<% month = now.strftime('%m') %>
<% d = now.at_beginning_of_month.at_beginning_of_week(:sunday) %>
<% 1.upto(6).each do |i| %>
  <tr height="80px">
<% (d..d.end_of_week(:sunday)).each do |c| %>
  <td align="left" valign="top" style="background: <%= (c == today) ? "#ffd0d0;" : "white" %>;">
    <%= (c.strftime('%m') == month) ? c.strftime('%d') : " " %><br>
    <% @sches.each do |sche| %>
      <% if c.strftime('%y-%m-%d') == sche.schedule_at.strftime('%y-%m-%d') %>
      <%= image_tag sche.icon.image_icon ,:height =>30 %>
      <% end %>
    <% end %>
  </td>
<% end %>
  </tr>
<% d = d + 1.week %>
<% end %>
</table>


<table>
  <thead>
    <tr>
      <div class="box22"><th><%= sortable "schedule_at", "日時" %></th></div>
      <div class="box22"><th>予定名</th></div>
      <div class="box22"><th><%= sortable "icon_id", "アイコン" %></th></div>
      <div class="box22"><th>場所</th></div>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sches.each do |sche| %>
      <% if sche.schedule_at < Date.today
           namecolor = "red"
        else
          if sche.schedule_at >= Date.today and sche.schedule_at <= Date.today + 5
            namecolor = "blue"
          else
            namecolor = "black"
          end
        end
       %>
      <% if sche.schedule_at >= Date.today - 7 and sche.schedule_at <= Date.today + 7 %> 
      <tr>
        <td><p style = "color : <%= namecolor %>">
        <% if sche.syujitsu == true %>
          <%= sche.schedule_at.strftime('20%y/%m/%d') %>
          終日
        <% else %>
          <%= sche.schedule_at.strftime('20%y/%m/%d %H:%M') %>
        <% end %></p></td>
        <td><%= sche.name_sche %></td>
        <td><%= image_tag sche.icon.image_icon ,:height =>35 %></td>
        <td><%= sche.place %></td>
        <td><%= link_to '詳細', sche ,target:"_self" %></td>
        <td><%= link_to '編集', edit_sch_path(sche), target:"_self" %></td>
        <td><%= link_to '削除', sche, method: :delete, data: { confirm: '削除しますか？' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'スケジュールの追加', new_sch_path , target:"_self" %>

app/views/sches/new.html.erb
<h1>新規スケジュール</h1>

<%= render 'form', sch: @sch %>

<%= link_to '戻る', :back , target:"_self" %>

app/views/sches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>日時：</strong>
  <% if @sch.syujitsu == true %>
    <%= @sch.schedule_at.strftime('20%y/%m/%d') %>
    ・終日
  <% else %>
    <%= @sch.schedule_at.strftime('20%y/%m/%d %H:%M') %>
  <% end %>
</p>

<p>
  <strong>予定名：</strong>
  <%= @sch.name_sche %>
</p>

<p>
  <strong>アイコン：</strong>
  <%= @sch.icon_id %>
</p>

<p>
  <strong>場所：</strong>
  <%= @sch.place %>
</p>

<p>
  <strong>メモ：</strong>
  <%= @sch.memo_sche %>
</p>

<p>
<strong>アプリ内通知：</strong>
<% if @sch.notification_sche == true %>
  オン
<% else %>
  オフ
<% end %>
</p>

<!--
<p>
  <strong>メール通知：</strong>
  <% if @sch.mail_sche == true %>
    オン
  <% else %>
    オフ
  <% end %>
</p>
-->

<p>
<strong>通知時間：</strong>
<% if @sch.notification_sche == true %>
  <%= @sch.notification_time.strftime('20%y/%m/%d %H:%M') %>
<% end %>
</p>

<!--
<p>
<strong>スヌーズ：</strong>
<% if @sch.notification_sche == true %>
  <% if @sch.snooze == true %>
    オン
  <% else %>
    オフ
  <% end %>
<% end %>
</p>
-->

<p>
  <strong>リンク：</strong>
  <%= link_to @sch.url_sche, @sch.url_sche %>
</p>

<%= link_to 'スケジュールへ', sches_path , target:"_self" %> |
<%= link_to '編集', edit_sch_path(@sch) , target:"_self" %> |
<%= link_to '通知画面へ', tuti_index_path , target:"_self" %> 