config/routes.rb
Rails.application.routes.draw do

  get 'serach/index'

  post 'serach/search'

  get 'list_g/index'

  resources :searches
  get 'tuti/index'

  get 'rink/index'

  resources :categories
  resources :syoji_ts
  resources :genres

  resources :syojis
  resources :syojis do
    member do
      get 'show_image'
    end
  end
  get 'menu/index'

  get 'logins/index'
  get 'logins/logoff'
  #resources :logins
  post 'logins/auth'
  resources :sche_ts
  resources :icons
  resources :icons do
    member do
      get'show_image'
    end 
  end
  resources :sches
  resources :users
  resources :users do
    member do
      get 'show_image'
    end
  end
  resources :genres
  resources :genres do
    member do
      get 'show_image'
    end
  end
  root 'tuti#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :syojis

end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :syojis, :foreign_key => "color_id"
end

app/models/icon.rb
class Icon < ApplicationRecord
  validate :error_check
  has_many :sches  
  def error_check
  end
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/sche.rb
class Sche < ApplicationRecord
  validate :error_check

  has_many :sche_ts

  belongs_to :icon

  def error_check
    # name_sche が空のときにエラーメッセージ
    if name_sche.blank?
       errors[:base] << '予定名は必ず入力してください'
    end

    # schedule_at が過去日のときエラーメッセージ
    if schedule_at < Time.now
      errors[:base] << '過去日は選択できません'
    end

    # notification_time が過去日か予定日以降のときエラーメッセージ
    if notification_sche == true or mail_sche == true
      if notification_time < Time.now
        errors[:base] << '過去日は選択できません'
      else
        if notification_time > schedule_at
          errors[:base] << '予定日より後は選択できません'
        end
      end
    end

  end

end

app/models/sche_t.rb
class ScheT < ApplicationRecord

  belongs_to :Sche

end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/syoji.rb
class Syoji < ApplicationRecord

    belongs_to :category
    belongs_to :genre, :foreign_key => "color_id"

    validate :error_check
    def error_check
      # title_syo が空のときにエラーメッセージ
      if title_syo.blank?
        errors[:base] << 'タイトルは必ず入力してください'
      end

      # notification_time が過去日か発売日以降のときエラーメッセージ
      if have == 3
        if notification_syo == true or mail_syo == true
          if notification_time < Time.now
              errors[:base] << '過去日は選択できません'
          else
            if notification_time > release
              errors[:base] << '発売日より後は選択できません'
            end
          end
        end
      end

      if have.blank?
        errors[:base] << '所持状態を入力してください'
      end
    end

end

app/models/syoji_t.rb
class SyojiT < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    validate :error_check
    def error_check

        if name_user.blank?
            errors[:base] << 'ユーザー名は必ず入力してください' 
        else
            if name_user.split(//).size > 20
                errors[:base] << 'ユーザー名は20文字以内で入力してください'
            end
        end
        if mail_user.blank?
            errors[:base] << 'メールアドレスは必ず入力してください'
        end
        if pass_user.blank?
            errors[:base] << 'パスワードは必ず入力してください'
        else
            if pass_user.split(//).length < 8
                errors[:base] << 'パスワードは８文字以上入力してください'
            end
        end
        unless pass_user.blank?
            a="#{pass_user}"=~/^[ぁ-んァ-ン一-龥]/
            if a != nil
                errors[:base] << 'パスワードは英数字のみで入力してください'
            end
        end
        unless mail_user.blank?
            a="#{mail_user}"=~/^[ぁ-んァ-ン一-龥]/
            if a != nil
                errors[:base] << 'メールアドレスは英数字のみで入力してください'
            end
        end
        unless mail_user.blank?
            a="#{mail_user}"=~/^[a-zA-Z0-9]+$/
            if a == nil
                errors[:base] << 'メールアドレスは半角で入力してください'
            end
        end
        unless pass_user.blank?
            a="#{pass_user}"=~/^[a-zA-Z0-9]+$/
            if a == nil
                errors[:base] << 'パスワードは半角で入力してください'
            end
        end


        #unless image_user.blank? 
            #case File.extname(image_user)
            #when ".png",".jpg",".jpeg",".bmp"
             #else
             #errors[:base] << '登録できる拡張子は png, jpg, jpeg,bmp です'
            #end
        #end
    end
    def self.authenticate(mail_user,pass_user)
        usr = find_by(mail_user: mail_user)
        if usr != nil && usr.pass_user == pass_user then
            usr
        else
            return
        end
    end
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  before_action :set_icon, only: [:show, :edit, :update, :destroy]

  # GET /icons
  # GET /icons.json
  def index
    @icons = Icon.all
  end

  # GET /icons/1
  # GET /icons/1.json
  def show
  end

  
  # GET /icons/new
  def new
    @icon = Icon.new
  end

  # GET /icons/1/edit
  def edit
  end

  # POST /icons
  # POST /icons.json
  def create
    @icon = Icon.new
    @icon.name_icon = params[:icon][:name_icon]

    if params[:icon][:image_icon].present?
      @icon.image_icon = params[:icon][:image_icon].original_filename
      @icon.image_type = params[:icon][:image_icon].content_type
      @icon.image_binary = params[:icon][:image_icon].read
    end

    if @icon.save
      redirect_to icons_path
    else
      render :new
    end
  end

  # PATCH/PUT /icons/1
  # PATCH/PUT /icons/1.json
  def update
    @icon = Icon.find(params[:id])
    @icon.name_icon = params[:icon][:name_icon]

    if params[:icon][:image_icon].present?
      @icon.image_icon = params[:icon][:image_icon].original_filename
      @icon.image_type = params[:icon][:image_icon].content_type
      @icon.image_binary = params[:icon][:image_icon].read
    end

    if @icon.save
      redirect_to icons_path
    else
      render :edit
    end
  end

def show_image
  @icon = Icon.find(params[:id])
  send_data @icon.image_binary, :filename => @icon.image_icon, :type => @icon.image_type, :disposition => 'inline'
end

  # DELETE /icons/1
  # DELETE /icons/1.json
  def destroy
    @icon.destroy
    respond_to do |format|
      format.html { redirect_to icons_url, notice: 'アイコンの削除に成功しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icon
      @icon = Icon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def icon_params
      params.require(:icon).permit(:name_icon, :image_icon, :image_binary, :image_type)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/list_g_helper.rb
module ListGHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/rink_helper.rb
module RinkHelper
end

app/helpers/sche_ts_helper.rb
module ScheTsHelper
end

app/helpers/sches_helper.rb
module SchesHelper
end

app/helpers/serach_helper.rb
module SerachHelper
end

app/helpers/syojis_helper.rb
module SyojisHelper
end

app/helpers/tuti_helper.rb
module TutiHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/icons/_form.html.erb
<%= form_with(model: icon, local: true) do |form| %>
  <% if icon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(icon.errors.count, "error") %> prohibited this icon from being saved:</h2>

      <ul>
      <% icon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :アイコン名 %>
    <%= form.text_field :name_icon, id: :icon_name_icon %>
  </div>

  <div class="field">
    <%= form.label :アイコン画像 %>
    <%= form.file_field :image_icon, id: :icon_image_icon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/icons/edit.html.erb
<h1>アイコン編集</h1>

<%= render 'form', icon: @icon %>

<%= link_to '詳細', @icon , target:"_self" %> |
<%= link_to '戻る', icons_path , target:"_self" %>

app/views/icons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>アイコン</h1>

<table>
  <thead>
    <tr>
      <th>アイコン名</th>
      <th>アイコン画像</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @icons.each do |icon| %>
      <tr>
        <td><%= icon.name_icon %></td>
        <td><%= image_tag show_image_icon_path(icon), :width => 100 %></td>
      
        <td><%= link_to '詳細', icon , target:"_self" %></td>
        <td><%= link_to '編集', edit_icon_path(icon) , target:"_self" %></td>
        <td><%= link_to '削除', icon, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規アイコン作成', new_icon_path , target:"_self" %>

app/views/icons/new.html.erb
<h1>新規アイコン作成</h1>

<%= render 'form', icon: @icon %>

<%= link_to '戻る', icons_path , target:"_self" %>

app/views/icons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>アイコン名:</strong>
  <%= @icon.name_icon %>
</p>

<p>
  <strong>アイコン画像:</strong>
  <%= @icon.image_icon %>
</p>

<%= link_to '編集', edit_icon_path(@icon) , target:"_self" %> |
<%= link_to '戻る', icons_path , target:"_self" %>